---
name: Cloud_utils
namespace: acme
tags:
  - cloud
  - aws
version: 1.0.0
readme: README.md
authors:
  - Automation Portal ACME
description: Cloud utility automation collection
license:
  - GPL-2.0-or-later
repository: https://github.com/Automation-Portal-ACME/acme-cloud-utils
